apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-admin-metrics-config
data:
  config.yml: |
    server:
      port: 3000
      data_dir: /app/data
    backend:
      ping_interval: 10000
    collector:
      batch_ms: 1000
      batch_max: 50
    debug_metrics: false
    storage:
      retention_days: 5
    epics:
      - name: "memory"
        poll_ms: 5000
      - name: "cpu"
        poll_ms: 5000
      - name: "commandlog_large_reply"
        poll_ms: 10000
      - name: "commandlog_large_request"
        poll_ms: 10000
      - name: "commandlog_slow"
        poll_ms: 10000
      - name: "slowlog_len"
        poll_ms: 60000
      - name: "monitor"
        monitoringDuration: 10000
        monitoringInterval: 10000
        maxCommandsPerRun: 1000000
