apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-admin-metrics-config
data:
  config.yml: |
    server:
      port: 3000
      data_dir: /app/data
    backend:
      ping_interval: 10000
    collector:
      batch_ms: 1000
      batch_max: 50
    debug_metrics: false
    storage:
      retention_days: 5
    epics:
      - name: "memory"
        type: "memory_stats"
        poll_ms: 5000
        file_prefix: "memory"
      - name: "cpu"
        type: "info_cpu"
        poll_ms: 5000
        file_prefix: "cpu"
      - name: "commandlog_large_reply"
        type: "commandlog_large_reply"
        poll_ms: 10000
        file_prefix: "commandlog_large_reply"
      - name: "commandlog_large_request"
        type: "commandlog_large_request"
        poll_ms: 10000
        file_prefix: "commandlog_large_request"
      - name: "commandlog_slow"
        type: "commandlog_slow"
        poll_ms: 10000
        file_prefix: "commandlog_slow"
      - name: "slowlog_len"
        type: "slowlog_len"
        poll_ms: 60000
        file_prefix: "slowlog_len"
      - name: "monitor"
        type: "monitor"
        monitoringDuration: 10000
        monitoringInterval: 10000
        maxCommandsPerRun: 1000000
        file_prefix: "monitor"
