blank_issues_enabled: true
contact_links:
  - name: Check existing issues
    url: https://github.com/valkey-io/valkey-admin/issues
    about: Please search existing issues before creating a new one to avoid duplicates
