services:
    metrics:
        build: .
        container_name: valkey-metrics
        environment:
            CONFIG_PATH: "/app/config.yml"
            PORT: "3000"
            DATA_DIR: "/app/data"
            VALKEY_HOST: ${VALKEY_HOST}
            VALKEY_PORT: ${VALKEY_PORT}
            VALKEY_USERNAME: ${VALKEY_USERNAME}
            VALKEY_PASSWORD: ${VALKEY_PASSWORD}
            VALKEY_TLS: ${VALKEY_TLS}
            VALKEY_VERIFY_CERT: ${VALKEY_VERIFY_CERT}
            BATCH_MS: "1000"
            BATCH_MAX: "50"
            DEBUG_METRICS: "1"
            LOG_LEVEL: "debug" # or info/warn/error/silent
            LOG_FORMAT: "pretty" # or json
        volumes:
            - ./config.yml:/app/config.yml:ro
            - ./data:/app/data
        ports:
            - "8080:3000"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        restart: unless-stopped

volumes:
    metrics_data:
