
import __ASTRO_IMAGE_IMPORT_BQNTr from "../../../assets/cluster_topology.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fcluster-topology.md";
import __ASTRO_IMAGE_IMPORT_Z2Cgrl from "../../../assets/command.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fcommand-interface.md";
import __ASTRO_IMAGE_IMPORT_Z9AVyO from "../../../assets/dashboard.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_1Kwl7t from "../../../assets/dashboard_charts.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fdashboard.md";
import __ASTRO_IMAGE_IMPORT_ZzStld from "../../../assets/key_browser.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fkey-browser.md";
import __ASTRO_IMAGE_IMPORT_ZmruP4 from "../../../assets/monitoring_hot_keys.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md";
import __ASTRO_IMAGE_IMPORT_Z2bhvWV from "../../../assets/monitoring_large_replies.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md";
import __ASTRO_IMAGE_IMPORT_ZCx0nK from "../../../assets/monitoring_large_requests.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md";
import __ASTRO_IMAGE_IMPORT_Cd0bT from "../../../assets/monitoring_slow_logs.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md";
import __ASTRO_IMAGE_IMPORT_Zwgkmy from "../../../assets/settings.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fsettings%2Fsettings.md";
import __ASTRO_IMAGE_IMPORT_1P4XAj from "../../assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx";
export default new Map([["../../../assets/cluster_topology.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fcluster-topology.md", __ASTRO_IMAGE_IMPORT_BQNTr], ["../../../assets/command.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fcommand-interface.md", __ASTRO_IMAGE_IMPORT_Z2Cgrl], ["../../../assets/dashboard.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_Z9AVyO], ["../../../assets/dashboard_charts.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fdashboard.md", __ASTRO_IMAGE_IMPORT_1Kwl7t], ["../../../assets/key_browser.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Fkey-browser.md", __ASTRO_IMAGE_IMPORT_ZzStld], ["../../../assets/monitoring_hot_keys.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md", __ASTRO_IMAGE_IMPORT_ZmruP4], ["../../../assets/monitoring_large_replies.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md", __ASTRO_IMAGE_IMPORT_Z2bhvWV], ["../../../assets/monitoring_large_requests.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md", __ASTRO_IMAGE_IMPORT_ZCx0nK], ["../../../assets/monitoring_slow_logs.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Ffeatures%2Factivity.md", __ASTRO_IMAGE_IMPORT_Cd0bT], ["../../../assets/settings.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fsettings%2Fsettings.md", __ASTRO_IMAGE_IMPORT_Zwgkmy], ["../../assets/logo.png?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx", __ASTRO_IMAGE_IMPORT_1P4XAj]]);
		